go:
    # Whenever the Go version is updated here,
    # .circle/config.yml should also be updated.
    version: 1.15
repository:
    path: github.com/prometheus/snmp_exporter
build:
    flags: -mod=vendor -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - snmp.yml
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - windows/amd64
        - windows/386
        - freebsd/amd64
        - freebsd/386
        - openbsd/amd64
        - openbsd/386
        - netbsd/amd64
        - netbsd/386
        - dragonfly/amd64
        - linux/arm
        - linux/arm64
        # Temporarily deactivated as golang.org/x/sys does not have syscalls
        # implemented for that os/platform combination.
        #- freebsd/arm
        #- openbsd/arm
        #- linux/mips64
        #- linux/mips64le
        - netbsd/arm
        - linux/ppc64
        - linux/ppc64le
